### PR TITLE
Adding to mhwd the version option

### PR DESCRIPTION
**Pull request by filipe-marques**
Hi!
I add to mhwd the version option, in the menu the options -v or --version, and created the necessary member functions.
I also add a member function to set the version and copyright more easily in main.cpp, that then will
show up, if the user request to show version. With the version and copyright also the user see what is the license.
Added to source files my name and email and also in authors file.
In todo file, could someone explain in more detail, what is to do? Because the list is unconcise.

Thanks!

### CODE REVIEW

**Comment by philmmanjaro** [comment]
So far so good. Can you fix the intentions as they are way of?

**Comment by philmmanjaro** [comment]
TODO is outdated. @december0123, can you update it if needed?

**Comment by Kirek** [comment]
Can you change functions and vars to CamelCase?
For example:
void Mhwd::set_version_mhwd(std::string version_of_software, std::string year_copyright)
to
void Mhwd::setVersionMhwd(std::string versionOfSoftware, std::string yearCopyright)

**Comment by philmmanjaro** [comment]
Right, I forgot about that on my review.

**Comment by december0123** [comment]
Thank you for your contribution. As Kirek stated, please remember to use the style that you see in the code.

**Comment by filipe-marques** [comment]
Ok, thanks for the recommendations, I will fix that.

**Comment by filipe-marques** [comment]
Do I need to close this pull request ?

**Comment by Kirek** [comment]
I think the commits done in your mhwd fork will automatically show up in the pull request, so you don't really need to.

**Comment by filipe-marques** [comment]
I made the changes to Camel Case convention, check the last commit.

**Comment by december0123** [comment]
Ok, I'll merge it now. About TODO, I'll look into it.

**Pull request merged**
